### PR TITLE
Update PCSX2 zstd workaround

### PR DESCRIPTION
**Pull request by illusionyy**

### CODE REVIEW

**Comment by chaoticgd** [comment]
This did need updating for the configuration files written out by the Qt frontend, but it doesn't make sense to have a path that's specific to your computer (since PCSX2 is cross-platform and can be portable) in the readme. Just having it as "... of your `PCSX2.ini` file." would be better I think.

**Comment by chaoticgd** [comment]
Maybe since at the time of writing the latest table release version of PCSX2 is 4 years old you should add a "(or `PCSX2_vm.ini` if you're still using an older version)" too.

**Comment by illusionyy** [comment]
Updated, I downloaded the newest nightly build and its the Qt version. Didn't check the stable so I didn't notice that it was still the old version.

**Comment by chaoticgd** [comment]
The grammar here is wrong: "you have to add `SavestateZstdCompression` to `false`". Also, in the initial version of my reply I said it was linked to whether it was wxWidgets/Qt, although I actually can't remember if that's exactly true, so maybe just omit that part (including the specific version number).

**Comment by illusionyy** [comment]
Okay. I reworded it more now.

> To work around this you have to change `SavestateZstdCompression` to `false` in the `EmuCore` section of your `PCSX2.ini`.
> If you are using an older version, you have to add `SavestateZstdCompression=disabled` to your `PCSX2_vm.ini` under `EmuCore` section.

**Pull request merged**
