### PR TITLE
CI: Use an up to date ghidra setup action

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**

### CODE REVIEW

**Comment by chaoticgd** [comment]
This looks useful. The version I was using before had an issue where it wouldn't use the right access token so would get rate limited by GitHub. Will this fix that or would you need to add a configuration option?

Also, could you pin this to a specific commit hash instead of a tag so I can review just that commit?

**Comment by antoniovazquezblanco** [comment]
Updated with the requested changes. Using the CI token will evade API rate limiting. I've also used the tag commit hash as requested. :)

**Comment by antoniovazquezblanco** [comment]
Hi @chaoticgd, have you had the time to look into this? :)

**Comment by chaoticgd** [comment]
> Hi @chaoticgd, have you had the time to look into this? :)

I'd forgotten about this. You may as well update it to a newer commit, then I can have a proper look.

**Comment by antoniovazquezblanco** [comment]
Done! :D

**Comment by chaoticgd** [comment]
Looks good.

**Pull request merged**
